### ISSUE TITLE
Implemented by GitHub

### ISSUE THREAD

**Issue by jerone** [MichaelSp/github-issue-votes.user.js#8]
This feature has now been [implemented](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) by GitHub. Still, this userscript is very useful for all older topics. Maybe you can duplicate the same interface GitHub is using...

**Comment by MichaelSp** [comment]
Sounds interesting. But as I'm not using this actively and my time is limited I'm not going to make this change. PR welcome though.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
